import type { Lead, Segment } from "./types";

// Trimmed sample dataset used as a fallback when a tool is invoked without
// a `leads` array. Mirrors the shape returned by the agent's Notion sync so
// the same widgets work for both real and demo data.
export const SAMPLE_LEADS: Lead[] = [
  {
    id: "sample-1",
    name: "Sample Lead 01",
    email: "sample.lead.01@example.invalid",
    role: "Product engineer",
    company: "Sample Company 01",
    workshop: "RAG & Data Chat",
    technical_level: "Developer",
    tools: ["LlamaIndex", "OpenAI"],
    status: "Not started",
    opt_in: true,
  },
  {
    id: "sample-2",
    name: "Sample Lead 02",
    email: "sample.lead.02@example.invalid",
    role: "Educator",
    company: "Sample Company 02",
    workshop: "MCP Apps / Tooling",
    technical_level: "Some technical",
    tools: ["CopilotKit", "Other"],
    status: "Not started",
    opt_in: true,
  },
  {
    id: "sample-3",
    name: "Sample Lead 03",
    email: "sample.lead.03@example.invalid",
    role: "Data platform engineer",
    company: "Sample Company 03",
    workshop: "RAG & Data Chat",
    technical_level: "Developer",
    tools: ["LlamaIndex", "LangChain", "OpenAI"],
    status: "Not started",
    opt_in: true,
  },
  {
    id: "sample-4",
    name: "Sample Lead 04",
    email: "sample.lead.04@example.invalid",
    role: "Founder",
    company: "Sample Company 04",
    workshop: "MCP Apps / Tooling",
    technical_level: "Some technical",
    tools: ["OpenAI", "Vercel AI SDK"],
    status: "Not started",
    opt_in: true,
  },
  {
    id: "sample-5",
    name: "Sample Lead 05",
    email: "sample.lead.05@example.invalid",
    role: "Engineering manager",
    company: "Sample Company 05",
    workshop: "Deploying Agents (prod)",
    technical_level: "Some technical",
    tools: ["LangChain", "OpenAI", "Vercel AI SDK"],
    status: "Not started",
    opt_in: true,
  },
  {
    id: "sample-6",
    name: "Sample Lead 06",
    email: "sample.lead.06@example.invalid",
    role: "Workshop facilitator",
    company: "Sample Company 06",
    workshop: "MCP Apps / Tooling",
    technical_level: "Developer",
    tools: ["CopilotKit", "Anthropic", "Vercel AI SDK"],
    status: "Not started",
    opt_in: true,
  },
  {
    id: "sample-7",
    name: "Sample Lead 07",
    email: "sample.lead.07@example.invalid",
    role: "Community lead",
    company: "Sample Company 07",
    workshop: "Not sure yet",
    technical_level: "Non-technical",
    tools: ["OpenAI", "Anthropic"],
    status: "Not started",
    opt_in: true,
  },
  {
    id: "sample-8",
    name: "Sample Lead 08",
    email: "sample.lead.08@example.invalid",
    role: "Designer",
    company: "Sample Company 08",
    workshop: "Agentic UI (AG-UI)",
    technical_level: "Some technical",
    tools: ["CopilotKit", "Other"],
    status: "Not started",
    opt_in: true,
  },
  {
    id: "sample-9",
    name: "Sample Lead 09",
    email: "sample.lead.09@example.invalid",
    role: "ML engineer",
    company: "Sample Company 09",
    workshop: "Evaluations & Guardrails",
    technical_level: "Advanced / expert",
    tools: ["LangChain", "Anthropic", "OpenAI"],
    status: "Not started",
    opt_in: false,
  },
  {
    id: "sample-10",
    name: "Sample Lead 10",
    email: "sample.lead.10@example.invalid",
    role: "Security engineer",
    company: "Sample Company 10",
    workshop: "Evaluations & Guardrails",
    technical_level: "Advanced / expert",
    tools: ["OpenAI", "LangChain"],
    status: "Not started",
    opt_in: true,
  },
  {
    id: "sample-11",
    name: "Sample Lead 11",
    email: "sample.lead.11@example.invalid",
    role: "CTO",
    company: "Sample Company 11",
    workshop: "Deploying Agents (prod)",
    technical_level: "Advanced / expert",
    tools: ["OpenAI", "LangChain", "Vercel AI SDK"],
    status: "Not started",
    opt_in: true,
  },
  {
    id: "sample-12",
    name: "Sample Lead 12",
    email: "sample.lead.12@example.invalid",
    role: "Data engineer",
    company: "Sample Company 12",
    workshop: "RAG & Data Chat",
    technical_level: "Advanced / expert",
    tools: ["LlamaIndex", "LangChain", "OpenAI"],
    status: "In progress",
    opt_in: false,
  },
];

export const SAMPLE_SEGMENTS: Segment[] = [];
